-- ============================================
-- coach.lab — Desactivar RLS para desarrollo
-- Ejecutar en Supabase SQL Editor si las tablas
-- devuelven vacío por políticas de seguridad
-- ============================================

ALTER TABLE team_contexts DISABLE ROW LEVEL SECURITY;
ALTER TABLE game_phases DISABLE ROW LEVEL SECURITY;
ALTER TABLE block_heights DISABLE ROW LEVEL SECURITY;
ALTER TABLE principles DISABLE ROW LEVEL SECURITY;
ALTER TABLE principle_contexts DISABLE ROW LEVEL SECURITY;
ALTER TABLE sub_principles DISABLE ROW LEVEL SECURITY;
ALTER TABLE behaviors DISABLE ROW LEVEL SECURITY;
ALTER TABLE behavior_contexts DISABLE ROW LEVEL SECURITY;
ALTER TABLE behavior_block_heights DISABLE ROW LEVEL SECURITY;
ALTER TABLE positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE field_zones DISABLE ROW LEVEL SECURITY;
ALTER TABLE position_behaviors DISABLE ROW LEVEL SECURITY;
ALTER TABLE glossary_terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE glossary_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE tactical_concepts DISABLE ROW LEVEL SECURITY;
ALTER TABLE tactical_concept_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_principles DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_sub_principles DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_game_phases DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_field_zones DISABLE ROW LEVEL SECURITY;
ALTER TABLE notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE note_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;
